# Generated by Django 6.0.2 on 2026-02-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('thumbnail_url', models.URLField()),
                ('backdrop_url', models.URLField(blank=True)),
                ('video_key', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=500)),
                ('views', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('release_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
