# Generated by Django 6.0.2 on 2026-02-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='has_free_preview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
