# Generated by Django 6.0.2 on 2026-02-12 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_duration_minutes_movie_has_free_preview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='backdrop_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trailer_key',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_key',
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop',
            field=models.ImageField(blank=True, help_text='Upload backdrop image (recommended: 1280x720px)', null=True, upload_to='movies/backdrops/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(help_text='Upload movie poster/thumbnail (recommended: 300x450px)', null=True, upload_to='movies/thumbnails/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_file',
            field=models.FileField(blank=True, help_text='Upload trailer video file (optional)', null=True, upload_to='movies/trailers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(help_text='Upload full movie video file', null=True, upload_to='movies/full/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='has_free_preview',
            field=models.BooleanField(default=True, help_text='Allow users to watch trailer for free', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.PositiveIntegerField(default=500, help_text='Price in RWF', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Trailer duration in seconds', null=True),
        ),
    ]
