# Generated by Django 6.0.2 on 2026-02-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_options_remove_movie_backdrop_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.JSONField(blank=True, default=list, help_text='List of actor names, e.g. ["Actor One", "Actor Two"]'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.JSONField(blank=True, default=list, help_text='List of genres, e.g. ["Action", "Drama"]'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.CharField(blank=True, help_text='Name of the movie producer', max_length=255, null=True),
        ),
    ]
