# Generated by Django 6.0.3 on 2026-03-22 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_add_cast_genres_producer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='producer_profile',
            field=models.ForeignKey(blank=True, help_text='Producer User Account', limit_choices_to={'role': 'Producer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
