# Generated by Django 6.0.3 on 2026-03-26 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_populate_producer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subtitles_file',
            field=models.FileField(blank=True, help_text='Upload subtitles file in VTT or SRT format (optional)', null=True, upload_to='movies/subtitles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['vtt', 'srt'])]),
        ),
    ]
