# Generated by Django 6.0.3 on 2026-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='momo_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='momo_provider',
            field=models.CharField(blank=True, choices=[('MTN', 'MTN'), ('Airtel', 'Airtel')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('MoMo', 'MoMo')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
