# Generated by Django 6.0.3 on 2026-04-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_withdrawalrequest_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deposit_id',
            field=models.CharField(blank=True, help_text='PawaPay deposit ID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Payer's phone number", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_id',
            field=models.CharField(blank=True, help_text='PawaPay payout ID (MoMo withdrawals only)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Processing', 'Processing'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
