# Generated by Django 6.0.3 on 2026-03-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Producer', 'Producer'), ('Viewer', 'Viewer')], db_index=True, default='Viewer', max_length=20),
        ),
    ]
