# Generated by Django 6.0.3 on 2026-04-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_adminauditlog_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='copyright_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
